name: Run PreMerge Checklist

on:
  pull_request:
    paths:
      - 'frontend/**'
    branches:
      - dev
      - main

jobs:
  run_tests_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Run linter
        run: |
          echo "changes detected in frontend folder"
          cd frontend/ 
          echo "Installing packages"
          npm install
          npm run lint
      - name: Run Build
        run: npm run build
